// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/2 01:27:33
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/project/mall/mall-pc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/plugins/**/*.{js,ts,mjs}","D:/project/mall/mall-pc/composables/**/*.{js,ts,mjs}","D:/project/mall/mall-pc/utils/**/*.{js,ts,mjs}","D:/project/mall/mall-pc/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/project/mall/mall-pc/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;